name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: read
  actions: read

jobs:
  docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get version
        id: version
        run: |
          VERSION=$(node -e "console.log(require('./package.json').version)")
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Build Docker image
        run: |
          docker build -t aperture-web:${{ steps.version.outputs.version }} .

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" |
          docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Tag and push docker images
        env:
          VERSION: ${{ steps.version.outputs.version }}
        run: |
          docker tag aperture-web:${VERSION} ${{ secrets.DOCKERHUB_USERNAME }}/aperture-web:${VERSION}
          docker tag aperture-web:${VERSION} ${{ secrets.DOCKERHUB_USERNAME }}/aperture-web:latest

          docker push ${{ secrets.DOCKERHUB_USERNAME }}/aperture-web:${VERSION}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/aperture-web:latest
